version: "3.8"

services:
  bungeecord:
    hostname: bungeecord
    container_name: bungeecord
    restart: unless-stopped
    image: itzg/bungeecord
    environment:
      TYPE: "VELOCITY"
      BUNGEE_JAR_REVISION: "1"
      CFG_MOTD: "The first minecraft server powered by ducks."
      REPLACE_ENV_VARIABLES: "true"
      ICON: "https://github.com/DuckHunt-discord/DHV4/blob/master/src/assets/Avatars/cartographer_duck_Calgeka.png?raw=true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: "25588"
    ports:
      - "25565:25577"
    volumes:
      - /root/mcbungeecord:/server
    networks:
      - database
      - minecraft

  mcmain:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    container_name: mcmain
    hostname: mcmain
    restart: unless-stopped
    ports:
      - "8123:8123"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      ## 81534 -> chunky
      # 1997 -> ProtocolLib
      # 111876 -> BetterGraves
      # 106031 -> ImageFrame
      # 80692 -> SurvivalInvisiframes
      # 81890 -> ContainerPassthrough
      # 102621 -> DNamePing Chat Pinging Plugin
      # 17311 -> WorldEditSelectionVisualizer
      # 14458 -> Ultimate Name Color
      # 88135 -> PlugManX
      # 111975 -> AxInventoryRestore
      SPIGET_RESOURCES: "1997,111876,106031,80692,81890,102621,17311,88135,111975"
      USE_AIKAR_FLAGS: "true"
      MEMORY: "6G"
      ONLINE_MODE: "FALSE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /root/mcdata:/data
    networks:
      - database
      - minecraft

  mcfunny:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    container_name: mcfunny
    hostname: mcfunny
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      # 1997 -> ProtocolLib
      # 106031 -> ImageFrame
      # 80692 -> SurvivalInvisiframes
      # 102621 -> DNamePing Chat Pinging Plugin
      # 17311 -> WorldEditSelectionVisualizer
      # 88135 -> PlugManX
      SPIGET_RESOURCES: "1997,106031,80692,102621,17311,88135"
      USE_AIKAR_FLAGS: "true"
      MEMORY: "1G"
      ONLINE_MODE: "FALSE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /root/mcfunny:/data
    networks:
      - database
      - minecraft


  psql_db:
    image: postgres:latest
    container_name: psqldb
    hostname: psqldb
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: "minecraft"
      POSTGRES_USER: "minecraft"
      POSTGRES_PASSWORD: "minecraft"
    volumes:
      - /root/psql_db:/var/lib/postgresql/data
    networks:
      - database


networks:
  minecraft:
  database:

